name: Continuous integration

on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        os: [windows-latest]
        python-version: [3.8]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8 
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        $CONDA/bin/conda install -c conda-forge rasterio=1.2.10
        $CONDA/bin/conda install -c conda-forge fiona=1.8.20
        python -m pip install -r requirements.txt 
    - name: Test with pytest
      run: |
        python -m pip install pytest
        python -m pytest -s ./tests
